---
# refresh fact cache of all servers
- hosts: all
  gather_facts: True

- hosts: servers
  roles:
    - common

- hosts: lxd_hosts
  roles:
    - lxd_host
    - role: users
      tags: users
      groups_for_roles:
        - role: admin
          groups: sudo,adm,lxd

- hosts: dub-registry.ci.lxd
  vars:
    - dub_registry_http_port: 8080
  roles:
    - dub_registry_mirror

- hosts: buildkite_agents
  vars_files:
    - vars/passwords.yml # buildkite_agent_token
  roles:
    - buildkite_agent

- hosts: buildkite_agents
  tasks:
    - name: test dependencies (1/2)
      apt: { name: "{{ item }}", install_recommends: no, update_cache: yes, cache_valid_time: 3600 }
      with_items:
        - build-essential
        - cmake
        - curl
        - gdb
        - git
        - jq
        - libblas-dev
        - libbz2-dev
        - libcairo-dev
        - libclang-4.0-dev # dstep
        - libcurl4-gnutls-dev
        - libevent-dev
        - libgcrypt20-dev
        - libgpg-error-dev
        - libgtk-3-0
        - liblapack-dev
        - liblzo2-dev
        - libopenblas-dev
        - libreadline-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - libzmq3-dev
        - llvm
        - mongodb-server
        - moreutils # sponge et.al.
        - pkg-config
        - python-dev
        - python-yaml
        - python3-nose
        - redis-server
        - rsync
        - unzip
      tags: deps
    - name: test dependencies (2/2)
      apt: { deb: "{{ item }}", install_recommends: no }
      with_items:
        - https://bintray.com/sociomantic-tsunami/dlang/download_file?file_path=libebtree6_6.0.s7-rc5-xenial_amd64.deb
        - https://bintray.com/sociomantic-tsunami/dlang/download_file?file_path=libebtree6-dev_6.0.s7-rc5-xenial_amd64.deb
        - https://bintray.com/sociomantic-tsunami/dlang/download_file?file_path=d1to2fix_0.10.0-alpha1-xenial_amd64.deb
      tags: deps
    - name: disable mongodb journaling
      lineinfile: { dest: /etc/mongodb.conf, regexp: "^{{ item.key }} *=", line: "{{ item.key }} = {{ item.value }}" }
      with_dict:
        journal: 'false'
        nojournal: 'true'
      notify: restart mongodb
    - name: use ld.gold
      alternatives: { name: ld, link: /usr/bin/ld, path: /usr/bin/ld.gold }
  handlers:
    - name: restart mongodb
      service: { name: mongodb, state: restarted }

- hosts: ci.dlang.io
  roles:
    - role: haproxy
      tags: haproxy
      backends:
        code-mirror.dlang.io: |
          mode http
          server s1 dub-registry.ci.lxd:8005
